version: '3.8'

services:
  project1:
    build: .
    volumes:
      - ./project1:/usr/src/app
    working_dir: /usr/src/app
    command: python -m flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  project2:
    build: .
    volumes:
      - ./project2:/usr/src/app
    working_dir: /usr/src/app
    command: python main.py
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  project3:
    build: .
    volumes:
      - ./project3:/usr/src/app
    working_dir: /usr/src/app
    command: python script.py
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  dev:
    build: .
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
